# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c64bba3a6c2d484e99f559bab3ed293b1945367ac888ac19e425640e70466d6280b1df6ea1579b9a1905cc3487a4fd6f6affda02d3e26a641eb08e0bff4df113

test:
  secret_key_base: 7cb9af34c60ed3d7d1ab7b648be82974e1f7a6fc8d5c3ef0d46053cce41f343981cdfa7113033aca391ec68c20f31f66fe06a080dcc43492e728f803d7ba6999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
